### ISSUE TITLE
Raw data is now split between 4 files instead of 3

### ISSUE THREAD

**Issue by choi-hannah** [epiforecasts/covid19.nhs.data#23]
Hello,

I noticed that the hospital admissions data is now split between 4 files:

Weekly Admissions and Beds up to 6 April 2021 (XLSX, 4.0MB) 
Weekly Admissions and Beds from 7 April up to 30 September 2021 (XLSX, 2.6MB) 
Weekly Admissions and Beds from 1 October 2021 up to 31 March 2022 (XLSX, 2.6MB) 
Weekly Admissions and Beds 11 August 2022 (XLSX, 1.9MB)

Could you please update `download_trust_data` to include this?

Thank you!

**Comment by sophiemeakin** [comment]
Thanks @choi-hannah for flagging and fixing this (#24)! 🥇
