### ISSUE TITLE
`get_admissions` is taking first admissions, not total admissions

### ISSUE THREAD

**Issue by choi-hannah** [epiforecasts/covid19.nhs.data#25]
Hello, I noticed that `get_admissions` is taking first admissions (patients admitted with COVID for the first time), and not total admissions (all patients admitted with COVID, regardless of whether they have any previous COVID admission/s). Is this as intended?

**Comment by sophiemeakin** [comment]
Thanks for pointing this out, Hannah. That is as intended (as it was originally designed for a very specific use case), but would probably be useful to add some flexibility now by adding an argument to `get_admissions` to choose either first or all admissions. Thoughts?
